# Generated by Django 4.2.28 on 2026-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
