# Generated by Django 4.2.28 on 2026-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_nom_user_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('superviseur', 'Superviseur'), ('commercial', 'Commercial'), ('technicien', 'Technicien'), ('comptable', 'Comptable')], max_length=20),
        ),
    ]
