# Generated by Django 4.2.28 on 2026-03-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0003_alter_commercial_options_commercial_user_account_and_more'),
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commercial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_profile', to='commercials.commercial'),
        ),
    ]
