# Generated by Django 6.0.2 on 2026-02-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vlan', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('statut', models.CharField(default='non_actif', max_length=20)),
                ('type_contrat', models.CharField(blank=True, choices=[('dedie', 'Dédié'), ('partage', 'Partagé'), ('symetrique', 'Symétrique'), ('asymetrique', 'Asymétrique'), ('autre', 'Autre')], max_length=20, null=True)),
                ('capacite', models.CharField(blank=True, max_length=5, null=True)),
                ('download', models.CharField(blank=True, max_length=5, null=True)),
                ('upload', models.CharField(blank=True, max_length=5, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.commercial')),
            ],
        ),
    ]
