# Generated by Django 4.2.28 on 2026-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_alter_activite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type_activite',
            field=models.CharField(choices=[('dementelement', 'Démantèlement'), ('survey', 'Survey'), ('installation', 'Installation'), ('investigation', 'Investigation'), ('maintenance', 'Maintenance'), ('tirage', 'Tirage'), ('raccordement', 'Raccordement'), ('remplacement', 'Remplacement'), ('noc support', 'Noc Support'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'activité"),
        ),
    ]
