# Generated by Django 4.2.28 on 2026-03-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techniciens', '0002_alter_technicien_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicien_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
