# Generated by Django 4.2.28 on 2026-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0003_technicien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
