# Generated by Django 6.0.2 on 2026-02-20 12:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        ('techniciens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du rapport')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_intervention_reelle', models.DateField(default=datetime.date.today, verbose_name="Date réelle d'intervention")),
                ('heure_debut_reelle', models.TimeField(blank=True, null=True, verbose_name='Heure début réelle')),
                ('heure_fin_reelle', models.TimeField(blank=True, null=True, verbose_name='Heure fin réelle')),
                ('travaux_realises', models.TextField(verbose_name='Travaux réalisés')),
                ('difficultes_rencontrees', models.TextField(blank=True, verbose_name='Difficultés rencontrées')),
                ('solutions_apportees', models.TextField(blank=True, verbose_name='Solutions apportées')),
                ('etat_avant', models.TextField(verbose_name='État avant intervention')),
                ('etat_apres', models.TextField(verbose_name='État après intervention')),
                ('equipements_utilises', models.TextField(blank=True, verbose_name='Équipements utilisés')),
                ('materiel_consomme', models.TextField(blank=True, verbose_name='Matériel consommé')),
                ('materiel_remplace', models.TextField(blank=True, verbose_name='Matériel remplacé')),
                ('parametres_configures', models.TextField(blank=True, verbose_name='Paramètres configurés')),
                ('qualite_signal', models.CharField(blank=True, max_length=50, verbose_name='Qualité du signal')),
                ('debit_constate', models.CharField(blank=True, max_length=50, verbose_name='Débit constaté')),
                ('client_present', models.BooleanField(default=True, verbose_name='Client présent')),
                ('satisfaction_client', models.IntegerField(blank=True, choices=[(1, '1 - Très insatisfait'), (2, '2 - Insatisfait'), (3, '3 - Moyen'), (4, '4 - Satisfait'), (5, '5 - Très satisfait')], null=True, verbose_name='Satisfaction client')),
                ('commentaire_client', models.TextField(blank=True, verbose_name='Commentaire client')),
                ('recommandations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('prochaine_action', models.CharField(blank=True, max_length=200, verbose_name='Prochaine action')),
                ('date_prochaine_intervention', models.DateField(blank=True, null=True, verbose_name='Date prochaine intervention')),
                ('photo_avant', models.ImageField(blank=True, null=True, upload_to='rapports/photos/avant/', verbose_name='Photo avant')),
                ('photo_apres', models.ImageField(blank=True, null=True, upload_to='rapports/photos/apres/', verbose_name='Photo après')),
                ('document_joint', models.FileField(blank=True, null=True, upload_to='rapports/documents/', verbose_name='Document joint')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('activite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='activites.activite', verbose_name='Activité concernée')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_activites', to='techniciens.technicien', verbose_name='Technicien')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Rapport d'activité",
                'verbose_name_plural': "Rapports d'activités",
                'db_table': 'activites_rapport',
                'ordering': ['-date_rapport'],
            },
        ),
    ]
