# Generated by Django 6.0.2 on 2026-02-20 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('specialite', models.CharField(choices=[('reseau', 'Réseau et Télécom'), ('vente', 'Vente et Marketing'), ('technique', 'Support Technique'), ('gestion', 'Gestion Clientèle'), ('autre', 'Autre')], default='vente', max_length=50, verbose_name='Spécialité')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
