# Generated by Django 4.2.28 on 2026-03-04 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercials', '0002_alter_commercial_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AddField(
            model_name='commercial',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='specialite',
            field=models.CharField(choices=[('reseau', 'Réseau et Télécom'), ('vente', 'Vente et Marketing'), ('technique', 'Support Technique'), ('gestion', 'Gestion Clientèle'), ('autre', 'Autre')], default='vente', max_length=50),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
